### ISSUE TITLE
Shiny webapp for gene mutations

### ISSUE THREAD

**Issue by pbiecek** [RTCGA/RTCGA#44]
These apps are prepared by students. 
They are very good illustrations what can be done with R and TCGA data

**Comment by pbiecek** [comment]
Here is an application that presents some analyses on gene mutations data

http://mi2.mini.pw.edu.pl:8080/RTCGA/DoBieGar/

**Comment by MarcinKosinski** [comment]
Someone made a great job with this app.
Would it be an issue to link to the Bioconductor source than to github ? http://bioconductor.org/packages/RTCGA.mutations/

it's a pitty that `survminer` is a young package and students probably didn't know that they could draw survival curves in `publication-ready` format, but it's ok. Maybe one done someone would provide PR to their source with the new method of plotting survival curves :
https://github.com/kassambara/survminer

Moreover it looks like the application is loading for some period of time at the beggining. Maybe one could add `loading image` so that a user would be aware that he or she needs to wait? http://stackoverflow.com/questions/18237987/show-that-shiny-is-busy-or-loading-when-changing-tab-panels

**Comment by pbiecek** [comment]
I do not think that we can count on any updates 
(unless we do them by ourselves).
So it will be take it or leave it. Let's wait for all apps and then we will see which are easy to use and provide useful information.

On the mi2 server there is ggplot2 in version 1.1 so survminer may not work properly
and there are reasons NOT to update ggplot2.

**Comment by MarcinKosinski** [comment]
Ok, so I'll take it, instead of leave it, of course.

**Comment by MarcinKosinski** [comment]
I've uploaded pictures of applications to RTCGA website : http://rtcga.github.io/RTCGA/Applications.html there are also links to applications available
