### ISSUE TITLE
Website: add info about data download

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA#60]

**Comment by hamdichau** [comment]
Dear MarcinKosinski

You are doing a great job!!!
some question.
now i am install the data package (2015-11),and how to update them newest.
I am interesting to the procedure or workflow that how you deal with the data from broadinstitute. 
for example, the data(ACC.mRNA), where the ACC.mRNA. dataframe come from, or how to process the origin data to such dataframe, 
because i try to use you datapackage to do some genomic research,so i need to know more about them and enable me to utilized them more strictly. 

Thank for your good job.
Hamdichau

**Comment by MarcinKosinski** [comment]
Hello @hamdichau ,

Thanks for message :)
Have you tried to check

````{R}
library(RTCGA.mRNA)
browseVignettes('RTCGA.mRNA')
````

There is full info about `RTCGA.mRNA` datasets preparation. 

Furthermoe I'm going to upload this section today http://rtcga.github.io/RTCGA/Download.html and to prepare datasets from the newest release

````{R}
> tail(checkTCGA('Dates'))
[1] "2015-02-04" "2015-04-02" "2015-06-01" "2015-08-21" "2015-11-01"
[6] "2016-01-28"
````

since there is a release from `2016-01-28`
